source 'https://rubygems.org'
gem 'github-pages'

gem 'execjs'
gem 'therubyracer', :platforms => :ruby



gem "jekyll", ">= 3.6.3"
gem "ffi", ">= 1.9.24"
gem "redcloth", ">= 4.3.0"
gem "yajl-ruby", ">= 1.3.1"
